* data-structures-in-common-lisp

This is a repository containing a survey of data structure availability / quality in Common Lisp.

For computer scientists, efficient implementations of some key data structures are the must.
Thanks to quicklisp, currently there are bunch of libraries available.
However, their quality varies --- some may use CLOS, some may be imperative, some are missing documents.

This project is somewhat similar in spirit to
http://eudoxia.me/article/common-lisp-sotu-2015/ . However, I do not plan
to propose any consolidation mainly because I believe the data structure
availability in common lisp is low, rather than "too high" that it is
difficult to choose which one to settle on, as in the case of application
tools such as web server, databases, GUI.

# Now, before proceeding, I do emphasize that I am not a Data Structure Ninja or sort of.

Any contributions are welcome. However, I do not like to make this tiny project like
Cliki, which contains bunch of outdated, unorganized information.
So, the material in the survey should better be a library already available in quicklisp.

